name: Assemble CI

on:
  push:
    branches:
      - master
    pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install binutils-arm-none-eabi
      run: sudo apt install binutils-arm-none-eabi
      
    - name: Install dependencies
      run: make
